// <auto-generated />
namespace Bridgeport_Library.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Addmembermodels : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addmembermodels));
        
        string IMigrationMetadata.Id
        {
            get { return "201904212102009_Add member models"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
